spring.application.name=project
server.port=9090

encryption.secret-key=Q8v3mK7xN2pL9sR4wT6yU1iO5aS0dF3gH6jK8lZ2xC4=

spring.datasource.url=jdbc:postgresql://localhost:5432/switch_monitoring
spring.datasource.username=switch_admin
spring.datasource.password=switch 1234
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true



spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/switch-monitoring